### ISSUE TITLE
不思議なダンジョン内の敵に倒された後、宿屋に戻りますがそこから一歩も動けなくなりメニューを開くとErrorが発生します。対象方が有れば教えて頂いても宜しいでしょうか？

### ISSUE THREAD

**Issue by majyu** [lriki/LN_MysteryRogueSystem#11]
> 他の質問と区別しやすくするため、タイトルには説明的な概要を書いてください。
>
> ❌ NG：
> * アイテムの作り方について
> * 助けてください
>
> 👍 OK：
> * 原作のアイテム 〇〇 を作りたいのですが、方法はありますか？
> * 敵キャラ 〇〇 の動きが原作と異なるようですが不具合でしょうか？
>
> 内容によっては、機能要望 や 不具合報告の情報の記入をお願いすることがあります。

**Comment by lriki** [comment]
@majyu HP becomes 0?

If so, it's a duplicate of #8.

**Comment by majyu** [comment]
> @majyu HP becomes 0?
> 
> If so, it's a duplicate of #8.
yes！HP becomes 0😖
