### ISSUE TITLE
[敵AI]部屋から１マス視界のダンジョン通路に入る際、敵に継続して追尾をしてほしい

### ISSUE THREAD

**Issue by shitsudok** [lriki/LN_MysteryRogueSystem#15]
> 他の提案と区別しやすくするため、タイトルには説明的な概要を書いてください。
>
> ❌ NG：
> * キャラクターの画像について
> * 効果音関連の要望
>
> 👍 OK：
> * 特定のステートが付加されているときに、キャラクターの画像を変更したい
> * 攻撃した時に効果音を再生したい

提案の理由と内容
----------

> リクエスト内容を書いてください
<img width="816" alt="スクリーンショット 2022-09-25 10 54 30" src="https://user-images.githubusercontent.com/47454270/192124942-2b9bf11e-6ab2-4c6a-81c1-8249d17d5482.png">

要望は表題の通りです。
上記のような画像の状況から、通路側に１歩移動すると、敵はそれ以上追いかけてきません。
このため、通路さえあれば全ての敵を振り切ることが可能となってしまっています。
不思議のダンジョンのゲーム性を鑑み、部屋から１マス視界のダンジョン通路に入る際、敵に継続して追尾をしていただくことを要望します。

期待する結果
----------

> どのような状態になったら解決したことになるかを書いてください。

部屋から１マス視界のダンジョン通路に入る際、敵が部屋の中に戻らず、主人公を通路側に追いかけるようになること

**Comment by lriki** [comment]
@shitsudok ご報告ありがとうございます！バグぽいですね…。対応させていただきます。
