### ISSUE TITLE
スライムと戦闘した際エラーが発生する

### ISSUE THREAD

**Issue by Dottoesky** [lriki/LN_MysteryRogueSystem#25]
Invalid entity type. (id: [93, 517486931])
Invalid entity type. (id: [74, 759630639])
Invalid entity type. (id: [190, 451667263])
上記のエラーが発生しました。数回プレイしていずれもスライムと戦闘時に発生しました。
攻撃自体はできて、3回目くらいの攻撃でエラーが出ます。

**Comment by lriki** [comment]
@Dottoesky ご報告ありがとうございます！
倒れた後にイベントを実行する処理の不具合でした。
こちら 80c2d6a6a87ed8e293e4a0200d833bdecbd68dc6 にて対策いたしました。
